### ISSUE TITLE
view stopped loading

### ISSUE THREAD

**Issue by rkohler8** [Tzanou123/vscode_tamagotchi_extension#2] opened 2023-12-18 22:57 UTC
'An error occurred while loading view: tamagotchi_garden'

view stopped loading. reverted to previous version, restarted, uninstalled and reinstalled and still not loading :(

**Comment by Tzanou123** [comment] 2024-01-07 23:11
Hello,
Sorry that you encounter issue
To help me to understand and debug Can you give me more details on this behaviour ?
What do you mean by "view stopped loading" ?

**Comment by eybrithingweird** [comment] 2024-03-06 00:13
Hello, got this issue just yesterday. Opened VS Code like normal, just to see the Tamagotchi window blank. Tried right-clicking > Hide 'Tamagotchi' and reloading it, shows this error:

![image_2024-03-06_081338803](https://github.com/tzanou-perso/vscode_tamagotchi_extension/assets/38281372/626b9ece-f036-4c92-9f8d-afbe16afd978)

Maybe there's anything I can do on my side to try and see its console or anything else?

**Comment by Tzanou123** [comment] 2024-03-06 00:25
> Hello, got this issue just yesterday. Opened VS Code like normal, just to see the Tamagotchi window blank. Tried right-clicking > Hide 'Tamagotchi' and reloading it, shows this error: ![image_2024-03-06_081338803](https://private-user-images.githubusercontent.com/38281372/310316667-626b9ece-f036-4c92-9f8d-afbe16afd978.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2ODQ5MzgsIm5iZiI6MTcwOTY4NDYzOCwicGF0aCI6Ii8zODI4MTM3Mi8zMTAzMTY2NjctNjI2YjllY2UtZjAzNi00YzkyLTlmOGQtYWZiZTE2YWZkOTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDAwMjM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxYzY3ZTlmMjRiMDQyZmE5NmE5ZjIyZjM5ZjAwNGRlYTU4MzY4MTU1OTJmMDYyYTZmZGEwZWM5ZjBkNjg1MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rLoORHscQyO5nw8p09f9tP3avNBWA1JFMe_eBbAw6Ms)
> 
> Maybe there's anything I can do on my side to try and see its console or anything else?

Thanks i think i can reproduce it, i will tell you if not

**Comment by Tzanou123** [comment] 2024-03-06 01:39
I upload a new release with patching the problem you relate ! Can you confirm after update the problems are gone ? I can then merge the branch ! 
Thanks

**Comment by eybrithingweird** [comment] 2024-03-06 03:42
Hello! I still got nothing. Doing the steps described in my previous comment no longer results in showing the error, just blank space right now. I've updated the extension, disabled then enabled it, plus updated my VS Code just to be sure. Also clicked spawn random boss and reset game, still doesn't show anything. I hope this helps!

**Comment by Tzanou123** [comment] 2024-03-06 10:10
can you press f1 then typing `developer: open webview developer tools` and then copy the content of your console ?

**Comment by eybrithingweird** [comment] 2024-03-08 07:01
> can you press f1 then typing `developer: open webview developer tools` and then copy the content of your console ?

Apologies for the late reply! Here's the console:
![image](https://github.com/tzanou-perso/vscode_tamagotchi_extension/assets/38281372/dd3e3a1d-e9e6-4659-a3f5-7e68f36ab873)

I'm using other extensions as well so the messages that were above what I sent are related to those.
Making it clearer: closed the extension and re-opened it, these were sent on the console:
![image](https://github.com/tzanou-perso/vscode_tamagotchi_extension/assets/38281372/a1e0b1f4-8ec8-4399-a0ef-b6f2121e54aa)

**Comment by Tzanou123** [comment] 2024-03-09 10:31
Thanks for your logs, but unfotunatly there is not much information on the error ! I try on my side to understand with my code and trying to reproduce but no luck on that ! If you can have a bit more details on wich part of the code the properties of undefined is ! It can be helpfull ! Can you try to click on the main-bundle.js link error on the top right corner of the log ?
I think it cant point the real problem because it is a compiled and minimified code but we need to try that

**Comment by eybrithingweird** [comment] 2024-03-09 12:06
> Thanks for your logs, but unfotunatly there is not much information on the error ! I try on my side to understand with my code and trying to reproduce but no luck on that ! If you can have a bit more details on wich part of the code the properties of undefined is ! It can be helpfull ! Can you try to click on the main-bundle.js link error on the top right corner of the log ? I think it cant point the real problem because it is a compiled and minimified code but we need to try that

Hello! Here's the main-bundle.js error:
![image](https://github.com/tzanou-perso/vscode_tamagotchi_extension/assets/38281372/54f896eb-8a52-43bb-b416-70bc034414f1)

**Comment by eybrithingweird** [comment] 2024-03-09 12:25
Short update: I noticed that the extension had a 'Reload Required' notice so I did just that, and now the console is logged with a loop of this error:
![image](https://github.com/tzanou-perso/vscode_tamagotchi_extension/assets/38281372/f0245eca-6f01-42c6-b820-62fb860e70fd)

The `Cannot read properties of undefined (reading 'texture')` error still shows up somewhere in the middle. 
Clicking on `main-bundle.js:253` shows this:
![image](https://github.com/tzanou-perso/vscode_tamagotchi_extension/assets/38281372/4f9977db-6f68-423e-9a9a-3f5911ec6ae8)

**Comment by Tzanou123** [comment] 2024-03-09 17:30
Thats strange, this code doesnt seems to come from my extension ! Do you have any other extension installed on  your vscode that is also a game  or may have a canvas js game ? If so can you tell me wich one ? and trying to unable it to see if its correcting the bug ?

**Comment by Tzanou123** [comment] 2024-03-09 17:41
After reviewing the vscode pets extension, The code you gave me seems to come from it, the strange fact is i try to install both on my side and i doesnt get your bug reproduced ! 
- can you tell me on wich platform you are (windos10, 11, macOs ...)
- Have you updated vscode-pets to latest version ?

**Comment by eybrithingweird** [comment] 2024-03-10 22:22
> After reviewing the vscode pets extension, The code you gave me seems to come from it, the strange fact is i try to install both on my side and i doesnt get your bug reproduced !
> 
> * can you tell me on wich platform you are (windos10, 11, macOs ...)
> * Have you updated vscode-pets to latest version ?

You're right, it's the vscode-pets extension, and I have it on the latest version on Windows 11. The `main-bundle.js` error still gets triggered after disabling the vscode-pets extension. I also tried uninstalling the vscode-pets and re-enabling Tamagotchi but the same error is still shown; Tamagotchi's canvas is still blank.

The issue didn't happen immediately, as both extensions were working for me until the day I commented on this post. It was working well for me for how many days (or even weeks? can't remember when I installed it).

EDIT: The second code screenshot I sent really wasn't from your extension; the looping `Uncaught: InvalidStateException {}` error on `main-bundle.js:253` is from this file:
`https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/HP/.vscode/extensions/tonybaloney.vscode-pets-1.25.1/media/main-bundle.js`

The `Cannot read properties of undefined (reading 'texture')` error on `main-bundle.js:2` is from this file:
`https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/HP/.vscode/extensions/tzanou.tamagotchi-0.4.3/media/main-bundle.js`

**Comment by eybrithingweird** [comment] 2024-03-10 22:38
Figured out how to do some changes on the code only on my side, so I went ahead to that file and tried placing `console.log(e[0])` to try and find the source of the error. Interestingly enough, after saving the changes, this new error popped up:
![image](https://github.com/tzanou-perso/vscode_tamagotchi_extension/assets/38281372/5f654e51-877e-4ea0-915b-9835aef4147d)

Going to that portion in `main-bundle.js:2` shows this:
![image](https://github.com/tzanou-perso/vscode_tamagotchi_extension/assets/38281372/88cb292a-0b51-4b62-bc9b-1cc3112212b7)

Placing `console.log(r)` before the error shows this on the console:
![image](https://github.com/tzanou-perso/vscode_tamagotchi_extension/assets/38281372/72ea168a-2d27-4e57-84e3-855f67e1ed3b)
(r.settings is undefined)

**Comment by Tzanou123** [comment] 2024-03-11 01:35
Hello,
First of all thank you very much for your kindness into helping me for resolving this issue !
I deploy a new version where i try to catch the error and let the extension anyway run if there is an error since if it is what i think the error come when we try to reload an old state of the game !
I also add a console log to be sure the error come where i think !
Can you please test it ? and give me the console log if the error still happen 

Thanks

**Comment by eybrithingweird** [comment] 2024-03-11 01:51
> Hello, First of all thank you very much for your kindness into helping me for resolving this issue ! I deploy a new version where i try to catch the error and let the extension anyway run if there is an error since if it is what i think the error come when we try to reload an old state of the game ! I also add a console log to be sure the error come where i think ! Can you please test it ? and give me the console log if the error still happen
> 
> Thanks

Hello, no problem at all!

The screen is now showing the game, but the data is back to zero! 
Here's the screenshot of the console:
![image](https://github.com/tzanou-perso/vscode_tamagotchi_extension/assets/38281372/eb3d46be-b32a-4c3b-aaa4-e9e877e9f02b)

EDIT: The other padding issue is now gone so far! Good job!
![image](https://github.com/tzanou-perso/vscode_tamagotchi_extension/assets/38281372/3e564e3c-ac7c-487e-8615-69661b3aa343)

**Comment by Tzanou123** [comment] 2024-03-11 01:59
Nice, 
Happy that the game is back for you .
Unfortunatly i think the old data from your game is gone, it was an error coming from it, maybe  a corrupted one from a previous version updated. Complicated to say exactly wich data since you had log from compiled code !
Anyway i will close this issue doesnt hesitate to contact me again if the error come again or if the data never saved when you reload vscode ! 
Thanks for your patience and enjoy the game ;)

**Closed as completed** 2024-03-11 23:39 UTC
Labels: bug, question
